name: Climbing Configured
type: feat
_id: 85fllWLdZyfq1P4o
img: icons/creatures/mammals/cat-hunched-glowing-red.webp
system:
  activities: {}
  uses:
    spent: 0
    recovery: []
    max: ''
  description:
    value: >-
      <p>Your remains are well configured for climbing, being light and with
      built in claws. You gain a climbing speed of 30 feet.</p>
    chat: ''
  identifier: climbing-configured
  source:
    revision: 1
    rules: '2024'
  enchant: {}
  type:
    value: race
    subtype: ''
  prerequisites:
    level: null
  properties: []
  requirements: Catfolk Remains
effects:
  - name: Climbing Configured
    img: icons/creatures/mammals/cat-hunched-glowing-red.webp
    origin: >-
      Compendium.kibbles-compendium-of-legends-and-legacies.kcll-feature-library.Item.85fllWLdZyfq1P4o
    _id: BU0aaAfuuCQMqyJq
    type: base
    system: {}
    changes:
      - key: system.attributes.movement.climb
        mode: 4
        value: '30'
        priority: null
    disabled: false
    duration:
      startTime: null
      seconds: null
      combat: null
      rounds: null
      turns: null
      startRound: null
      startTurn: null
    description: ''
    tint: '#ffffff'
    transfer: true
    statuses: []
    sort: 0
    flags: {}
    _stats:
      compendiumSource: null
      duplicateSource: null
      coreVersion: '12.331'
      systemId: dnd5e
      systemVersion: 4.1.1
      createdTime: 1732224370903
      modifiedTime: 1732224379550
      lastModifiedBy: pJeIW7qCa0HkURWq
    _key: '!items.effects!85fllWLdZyfq1P4o.BU0aaAfuuCQMqyJq'
folder: null
sort: 19700000
ownership:
  default: 0
  pJeIW7qCa0HkURWq: 3
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  coreVersion: '12.331'
  systemId: dnd5e
  systemVersion: 4.1.1
  createdTime: 1732220518957
  modifiedTime: 1732224368214
  lastModifiedBy: pJeIW7qCa0HkURWq
_key: '!items!85fllWLdZyfq1P4o'

